"""Render the HTML report to Markdown — same numbers, one source.

The report's prose and figures are generated by build_report.py; duplicating that
text in a second template would guarantee the two drift apart. So this converts
the built page instead: headings, paragraphs, tables and lists carry over, SVG
figures become a line naming the figure and its caption.

    uv run python scripts/build_report.py          # writes results/stageb-report.html
    uv run python scripts/report_to_markdown.py    # writes results/stageb-report.md
"""
from __future__ import annotations

import argparse
import re
from html import unescape
from html.parser import HTMLParser
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_BLOCK = {"h1", "h2", "p", "li", "caption", "figcaption", "td", "th"}


class _Md(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.out: list[str] = []
        self._buf: list[str] = []
        self._stack: list[tuple[str, dict]] = []
        self._row: list[str] = []
        self._table: list[list[str]] = []
        self._head = False
        self._skip = 0

    # ── helpers ──────────────────────────────────────────────────────────────
    def _cls(self, depth=1):
        return self._stack[-depth][1].get("class", "") if len(self._stack) >= depth else ""

    def _flush(self) -> str:
        t = re.sub(r"\s+", " ", "".join(self._buf)).strip()
        self._buf = []
        return t

    def _in(self, name):
        return any(t == name for t, _ in self._stack)

    # ── parsing ──────────────────────────────────────────────────────────────
    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == "footer":
            self.out.append("\n---\n\n**出典・注記**\n")
        if tag in ("style", "script", "svg"):
            self._skip += 1
            return
        if self._skip:
            return
        self._stack.append((tag, a))
        if tag in _BLOCK or (tag == "div" and ("tile" in a.get("class", "") or self._in("footer"))):
            self._buf = []
        elif tag == "span" and self._in("div") and a.get("class") == "sub":
            self._buf.append(" — ")
        elif tag in ("strong", "b"):
            self._buf.append("**")
        elif tag == "em":
            self._buf.append("*")
        elif tag == "table":
            self._table, self._head = [], False
        elif tag == "thead":
            self._head = True
        elif tag == "tr":
            self._row = []

    def handle_endtag(self, tag):
        if tag in ("style", "script", "svg"):
            self._skip = max(0, self._skip - 1)
            return
        if self._skip:
            return
        cls = self._cls()
        if tag in ("strong", "b"):
            self._buf.append("**")
        elif tag == "em":
            self._buf.append("*")
        elif tag == "h1":
            self.out.append(f"# {self._flush()}\n")
        elif tag == "h2":
            self.out.append(f"\n## {self._flush()}\n")
        elif tag in ("td", "th"):
            self._row.append(self._flush())
        elif tag == "tr":
            if self._row:
                self._table.append(self._row)
            self._row = []
        elif tag == "thead":
            self._head = False
        elif tag == "caption":
            self.out.append(f"\n**{self._flush()}**\n")
        elif tag == "table":
            self._emit_table()
        elif tag == "li":
            txt = self._flush()
            self.out.append(f"- {txt}" if txt else "")
        elif tag == "figcaption":
            self.out.append(f"\n> 図 — {self._flush()}\n")
        elif tag == "dt":
            self._buf.append(": ")
        elif tag == "dd":
            self._buf.append(" · ")
        elif tag == "div" and ("tile" in cls or self._in("footer")):
            txt = self._flush()
            if txt:
                self.out.append(f"- {txt}")
        elif tag == "dl":
            self.out.append("\n" + self._flush().rstrip(" ·") + "\n")
        elif tag == "p":
            txt = self._flush()
            if not txt:
                pass
            elif "eyebrow" in cls:
                self.out.append(f"\n**{txt}**\n")
            elif "callout" in cls:
                self.out.append("\n> " + txt.replace("\n", "\n> ") + "\n")
            else:
                self.out.append(f"\n{txt}\n")
        elif tag in ("section", "header"):
            self.out.append("\n---\n")
        if self._stack and self._stack[-1][0] == tag:
            self._stack.pop()

    def handle_data(self, data):
        if self._skip:
            return
        if self._cls() == "lab":                        # stat-tile label
            self._buf.append(f"**{data.strip()}**: ")
            return
        if self._cls() == "lead":                       # argument-step label
            self._buf.append(f"**{data.strip()}** — ")
            return
        if self._stack and self._stack[-1][0] in ("summary",):
            self.out.append(f"\n**{data.strip()}**\n")
            return
        self._buf.append(data)

    def _emit_table(self):
        if not self._table:
            return
        w = max(len(r) for r in self._table)
        rows = [r + [""] * (w - len(r)) for r in self._table]
        head, body = rows[0], rows[1:]
        self.out.append("")
        self.out.append("| " + " | ".join(head) + " |")
        self.out.append("|" + "---|" * w)
        for r in body:
            self.out.append("| " + " | ".join(r) + " |")
        self.out.append("")
        self._table = []


def convert(html: str) -> str:
    p = _Md()
    p.feed(html)
    md = "\n".join(p.out)
    md = re.sub(r"\n{3,}", "\n\n", md)
    md = re.sub(r"(\n---\n)(\s*\n---\n)+", r"\1", md)
    return unescape(md).strip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--html", default=str(_ROOT / "results" / "stageb-report.html"))
    ap.add_argument("--out", default=str(_ROOT / "results" / "stageb-report.md"))
    a = ap.parse_args()
    src = Path(a.html)
    if not src.is_file():
        raise SystemExit(f"{src} not found — run scripts/build_report.py first")
    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    md = convert(src.read_text(encoding="utf-8"))
    note = ("> この Markdown は `results/stageb-report.html` から生成しています。"
            "図は SVG のため本文には含まれません——各図の位置には「図 —」で始まる"
            "キャプション行が残してあり、図そのものは HTML 版で参照できます。\n\n")
    lines = md.split("\n")
    cut = next((i for i, l in enumerate(lines) if l.startswith("# ")), 0) + 1
    md = "\n".join(lines[:cut]) + "\n\n" + note + "\n".join(lines[cut:])
    out.write_text(md, encoding="utf-8")
    print(f"wrote {out}  ({len(md):,} chars, {md.count(chr(10)) + 1} lines)")


if __name__ == "__main__":
    main()
